[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Exclude .js file extensions from the redirect rule
  force = true
  conditions = {Path: ["!/*.js"]}

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
