[build]
  command = "npm run build"
  publish = "vanilla-project"
  base = "/"
  memory = "2048"

  [build.environment]
    NODE_VERSION = "18.13.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
