[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Exclude .js and .css file extensions from the redirect rule
  force = true
  conditions = {Path: ["!/*.js", "!/*.css"]}

[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Include the public folder
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
